server {
    listen 8000;
    server_name localhost;

    # Logic utama
    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        try_files $uri $uri/ /index.html;
    }

    # Cache Control: Biar config gak nyangkut di browser
    location = /env-config.js {
        root /usr/share/nginx/html;
        add_header Cache-Control "no-cache";
    }

    # Error pages
    error_page 500 502 503 504 /50x.html;
    location = /50x.html {
        root /usr/share/nginx/html;
    }
}